### ISSUE TITLE
Panics when Sweep rate is larger than val

### ISSUE THREAD

**Issue by ErikReider** [VoltaireNoir/blight#1]
https://github.com/VoltaireNoir/blight/blob/c1d2f02b07ad5eedaca41e788bf9952775ac5585/src/lib.rs#L293

**Comment by VoltaireNoir** [comment]
@ErikReider Thanks for reporting it. I'll be fixing it soon. 

By the way, as a user of the library, do you feel that the sweep function is a little confusing to work with? I'm thinking about turning it into a method on the Device struct. That would also simplify the function signature.

**Comment by ErikReider** [comment]
The sweep function worked fine for me. There was just a delay in my UI when waiting for the sweep to complete but that issue is on my end to fix :)
